.\" Manpage for len.
.TH man 6 "11 March 2016" "1.2" "Nonstandard Utility: \fBlen\fR"
.SH NAME
.PP
\fBlen\fR \- ensure the line lengths of a plaintext file are within a certain range. Originally intended for source code.
.SH SYNOPSIS
\fBlen\fR \-h
.PP
\fBlen\fR \-\-help
.TP
\fBlen\fR [\fIOPTIONS\fR] \fIFILES\fR
.SH DESCRIPTION
.PP
Scan through text files and check if the lengths of all lines (delimited by newline characters) are within a certain range. \fBlen\fR can process multiple files in a single invocation.
.PP
Specify \fI\-\fR in place of \fIFILE\fR to read from \fBstdin\fR.
.PP
By default, \fBlen\fR does not produce any output.
.PP
\fBlen\fR can print all lines that meet the criteria, all lines that do not meet the criteria, or print all lines.
.SH OPTIONS
Mandatory arguments to long options are mandatory for short options as well. Short options that do not require arguments may be combined.
.TP
\fB\-m, \-\-max\fR \fIMAX_LINE_LENGTH\fR
Set the upper limit of line lengths. This cannot be negative or less than the lower limit, described below. Defaults to 80 characters.
.TP
\fB\-M, \-\-min\fR \fIMIN_LINE_LENGTH\fR
Set the lower limit of line lengths. This cannot exceed the upper limit. Defaults to 1 character. Newline characters are
counted.
.TP
\fB\-t, \-\-tab\-width\fR \fITAB_WIDTH\fR
Set the number of spaces a tab character is considered equivalent to. Defaults to 8 characters.
.TP
\fB\-p, \-\-print\-offenders\fR
Print lines that do not meet line length criteria. When multiple files are specified, lines are reported in sections with filename headers in the format \-\-|FILENAME|\-\-. Can be specified alongside \-P to print all
lines from all files.
.TP
\fB\-P, \-\-print\-matches\fR
Print lines that meet line length criteria. When multiple files are specified, lines are reported in sections with filename headers in the format \-\-|FILENAME|\-\-. Can be specified with \-p to print all lines
from all files.
.TP
\fB\-n, \-\-line\-numbers\fR
Prefix lines with line numbers. Has no effect unless one or both of \-p and \-P are specified.
.TP
\fB\-c, \-\-color\fR
Turns on color. Has no effect unless one or both of \-p and \-P are specified.
.TP
\fB\-r, \-\-truncate\fR
Truncates lines longer than \fIMAX_LINE_LENGTH\fR to a length of \fIMAX_LINE_LENGTH\fR and postfixes them with a '+'.
.TP
\fB\-l, \-\-line\-lengths\fR
Displays line lengths. Has no effect unless one or both of \-p and \-P are specified.
.TP
\fB\-N, \-\-count\-newlines\fR
Counts newlines when calculating line lengths. Note that all newline sequences are transformed into a single newline character '\\n.' When specified with \-c, colors change one character earlier, so that the correct number of characters are colored. For example, if the newline is the 81st character in the line and \fIMAX_LINE_LENGTH\fR is 80, the 80 character will be colored. Off by default.
.TP
\fB\-h, \-\-help\fR
Display help and exit.
.SH EXAMPLES
.TP
\fBlen\fR \fIFILE\fR
Checks \fIFILE\fR to make sure all lines are between 1 and 80 characters long (default behavior).
.TP
\fBlen\fR \fIFILE1\fR \fIFILE2\fR \fI...\fR
Checks that all lines in all files named are within tolerance.
.TP
\fBlen\fR \fB\-m\fR \fIMAX_LINE_LENGTH\fR \fB\-M\fR \fIMIN_LINE_LENGTH\fR \fIFILE\fR
Checks FILE to make sure all lines are between \fIMIN_LINE_LENGTH\fR and \fIMAX_LINE_LENGTH\fR characters long.
.TP
\fBlen\fR \fB\-np\fR \fIFILE\fR
Checks \fIFILE\fR, prints all lines that are out of tolerance, and gives line
numbers
.TP
\fBlen\fR \fB\-npr\fR \fIFILE\fR
Truncates long lines instead of showing full lines.
.TP
\fBlen\fR \fB\-P\fR \fIFILE\fR
Checks \fIFILE\fR and prints out all lines whose lengths are within tolerance.
.TP
\fBlen\fR \fB\-pP\fR \fIFILE\fR
Checks \fIFILE\fR and prints out the entire contents of \fIFILE\fR.
.SH EXIT STATUS
.TP
.B 0
All lines in all files were in tolerance
.TP
.B 1
At least one line among all lines read was out of tolerance
.TP
.B 100
Cannot combine options that require arguments
.TP
.B 101
Unrecognized option
.TP
.B 102
Unable to allocate sufficient memory
.TP
.B 103
Could not open specified file
.TP
.B 104
Missing an argument to a flag
.TP
.B 105
No options or arguments given to program
.SH AUTHOR
.PP
Written by Wesley Wei
